### ISSUE TITLE
Milestones for CODEX

### ISSUE THREAD

**Issue by DEADSEC-SECURITY** [DEADSEC-SECURITY/CODEX#1]
- [x] SETUP
    
  - [x] Add Package and Dependency Installer
-------------------------------------------------------------------------------------------
- [ ] WEB [WORK IN PROGRESS] [NEED HELP]

   - [ ] Create SQL Injection
   - [ ] Full website attack / vunerability detection
-------------------------------------------------------------------------------------------
- [ ] NET

   - [x] Add HandShake Menu
   - [ ] Evil Twin Attack [NEED HELP]
   - [x] Target Selection (airodum-ng)
   - [x] DOS Menu
   - [x] Monitor / Manged mode 
-------------------------------------------------------------------------------------------
- [x] MAIN

   - [x] Detection of Admin privileges (ROOT)
-------------------------------------------------------------------------------------------
- [ ] BRUTEFORCE

   - [x] WPA and WPA2 Decrypt Menu
   - [ ] SHA-256, MD5 ...
-------------------------------------------------------------------------------------------
- [x] MODULES

   - [x] Airodump-ng
   - [x] NMAP

CODEX Packages and dependencies:

LINUX:
   - aircrack-ng
   - MDK3
   - HashCat
   - whois

PYTHON:
   - os
   - sys
   - json
   - netifaces
   - subprocess
   - pandas
   - tld
